# Generated by Django 3.1 on 2020-11-21 10:46

from django.db import migrations
import imagekit.models.fields
import tmuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmuser', '0002_auto_20201121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmuser',
            name='id_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=tmuser.models.image_upload_to),
        ),
    ]
