# Generated by Django 3.1 on 2020-11-21 10:47

from django.db import migrations
import imagekit.models.fields
import tmuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmuser', '0003_tmuser_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='id_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=tmuser.models.image_upload_to, verbose_name='학생증 사진'),
        ),
    ]
