# Generated by Django 3.1.1 on 2020-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmuser', '0001_initial'),
        ('ddat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to='tmuser.Tmuser'),
        ),
    ]
