# Generated by Django 3.1 on 2020-11-21 10:26

import ddat.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddat', '0002_auto_20201108_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='campus',
            field=models.CharField(default='논산 캠퍼스', max_length=32, verbose_name='캠퍼스 구분'),
        ),
        migrations.AddField(
            model_name='market',
            name='select_name',
            field=models.CharField(default='익명', max_length=16, verbose_name='익명/실명'),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=ddat.models.image_upload_to),
        ),
    ]
