# Generated by Django 3.1 on 2020-11-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('market_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ddat.market')),
            ],
            options={
                'verbose_name': '소모임',
                'verbose_name_plural': '소모임',
                'db_table': 'group',
            },
            bases=('ddat.market',),
        ),
        migrations.CreateModel(
            name='Handcraft',
            fields=[
                ('market_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ddat.market')),
            ],
            options={
                'verbose_name': '공예품장',
                'verbose_name_plural': '공예품장',
                'db_table': 'handcraft',
            },
            bases=('ddat.market',),
        ),
        migrations.CreateModel(
            name='TalentMarket',
            fields=[
                ('market_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ddat.market')),
            ],
            options={
                'verbose_name': '재능장',
                'verbose_name_plural': '재능장',
                'db_table': 'talent_market',
            },
            bases=('ddat.market',),
        ),
    ]
