# Generated by Django 3.1 on 2020-11-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1', max_length=64, verbose_name='쪽지 제목')),
                ('content', models.TextField(default='1', verbose_name='내용')),
                ('market', models.CharField(blank=True, default='', max_length=64, verbose_name='관련 장/모임 이름')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_receiver', to='tmuser.tmuser')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_writer', to='tmuser.tmuser')),
            ],
            options={
                'verbose_name': '쪽지',
                'verbose_name_plural': '쪽지',
                'db_table': 'Note',
            },
        ),
    ]
