# Generated by Django 3.1 on 2020-11-06 15:17

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to=notice.models.image_upload_to)),
                ('content', models.TextField(verbose_name='공지 내용')),
                ('writer', models.CharField(max_length=8, verbose_name='작성자')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified_dttm', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talentmarket_main', models.TextField(default='기본값', verbose_name='재능장 메인 설명')),
                ('group_main', models.TextField(default='기본값', verbose_name='소모임 메인 설명')),
                ('handcraft_main', models.TextField(default='기본값', verbose_name='소공예품 메인 설명')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='market.group')),
                ('handcraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handcraft', to='market.handcraft')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='notice.noticemodel')),
                ('talentmarket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talentmarket', to='market.talentmarket')),
            ],
            options={
                'verbose_name': '게시판 메인',
                'verbose_name_plural': '게시판 메인',
                'db_table': 'main',
            },
        ),
    ]
