# Generated by Django 3.1 on 2020-11-06 15:17

import board.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('description', models.TextField(default='', verbose_name='설명')),
                ('writer', models.CharField(max_length=8, verbose_name='작성자')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified_dttm', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '내용',
                'verbose_name_plural': '내용',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='이름')),
                ('usernickname', models.CharField(max_length=32, verbose_name='닉네임')),
                ('useremail', models.EmailField(max_length=128, verbose_name='이메일')),
                ('phonenumber', models.CharField(default='기본값', max_length=16, verbose_name='연락처')),
                ('department_name', models.CharField(max_length=64, verbose_name='학과')),
                ('student_number', models.CharField(max_length=8, verbose_name='학번')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('answered', models.CharField(default='N', max_length=4, verbose_name='답변 여부')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified_dttm', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '사용자 문의사항',
                'verbose_name_plural': '사용자 문의사항',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=board.models.image_upload_to)),
                ('order', models.SmallIntegerField()),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.content')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ddat.market')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='답변 제목')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='board.questions')),
            ],
            options={
                'verbose_name': '문의 답변',
                'verbose_name_plural': '문의 답변',
                'db_table': 'answer',
            },
        ),
    ]
