# Generated by Django 3.1.1 on 2020-11-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddat', '0002_auto_20201108_0136'),
        ('tmuser', '0001_initial'),
        ('board', '0003_auto_20201109_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddat.market')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmuser.tmuser')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'comment',
            },
        ),
    ]
