# Generated by Django 3.1.1 on 2020-11-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='market',
        ),
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='board.image'),
            preserve_default=False,
        ),
    ]
