# Generated by Django 3.1.1 on 2020-11-11 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20201112_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
        migrations.AddField(
            model_name='comment',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
    ]
