# Generated by Django 3.1 on 2020-11-21 10:42

import board.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20201112_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=board.models.image_upload_to),
        ),
    ]
